name: Find related issues

permissions: 
  issues: write

on:
  issues:
    types: [opened]

jobs:
  find-related:
    # This job only runs for pull request comments
    name: Find Related Issues
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - uses: actions/cache@v3
        id: cache
        with:
          path: embeddings.csv
          key: embeddings.csv
      - name: Copy embeddings from s3
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          aws s3 cp s3://mybucket-edbd356/embeddings.csv .
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      - run: python find_related_issues.py --url ${{ github.event.issue.url}} --output-file output.txt
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY}}
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: output.txt